import { MenuType } from "./menuType";

export const genres : MenuType[] =  [
    { name: 'Action', path: 'action' },
    { name: 'Adult Cast', path: 'adult-cast' },
    { name: 'Adventure', path: 'adventure' },
    { name: 'Anthropomorphic', path: 'anthropomorphic' },
    { name: 'Avant Garde', path: 'avant-garde' },
    { name: 'Boys Love', path: 'shounen-ai' },
    { name: 'Cars', path: 'cars' },
    { name: 'CGDCT', path: 'cgdct' },
    { name: 'Childcare', path: 'childcare' },
    { name: 'Comedy', path: 'comedy' },
    { name: 'Comic', path: 'comic' },
    { name: 'Crime', path: 'crime' },
    { name: 'Crossdressing', path: 'crossdressing' },
    { name: 'Cultivation', path: 'cultivation' },
    { name: 'Delinquents', path: 'delinquents' },
    { name: 'Dementia', path: 'dementia' },
    { name: 'Demons', path: 'demons' },
    { name: 'Detective', path: 'detective' },
    { name: 'Drama', path: 'drama' },
    { name: 'Dub', path: 'dub' },
    { name: 'Ecchi', path: 'ecchi' },
    { name: 'Educational', path: 'educational' },
    { name: 'Erotica', path: 'erotica' },
    { name: 'Family', path: 'family' },
    { name: 'Fantasy', path: 'fantasy' },
    { name: 'Gag Humor', path: 'gag-humor' },
    { name: 'Game', path: 'game' },
    { name: 'Gender Bender', path: 'gender-bender' },
    { name: 'Gore', path: 'gore' },
    { name: 'Gourmet', path: 'gourmet' },
    { name: 'Harem', path: 'harem' },
    { name: 'Hentai', path: 'hentai' },
    { name: 'High Stakes Game', path: 'high-stakes-game' },
    { name: 'Historical', path: 'historical' },
    { name: 'Horror', path: 'horror' },
    { name: 'Idols (Female)', path: 'idols-female' },
    { name: 'Isekai', path: 'isekai' },
    { name: 'Iyashikei', path: 'iyashikei' },
    { name: 'Josei', path: 'josei' },
    { name: 'Kids', path: 'kids' },
    { name: 'Love Polygon', path: 'love-polygon' },
    { name: 'Magic', path: 'magic' },
    { name: 'Magical Sex Shift', path: 'magical-sex-shift' },
    { name: 'Mahou Shoujo', path: 'mahou-shoujo' },
    { name: 'Martial Arts', path: 'martial-arts' },
    { name: 'Mecha', path: 'mecha' },
    { name: 'Medical', path: 'medical' },
    { name: 'Military', path: 'military' },
    { name: 'Music', path: 'music' },
    { name: 'Mystery', path: 'mystery' },
    { name: 'Mythology', path: 'mythology' },
    { name: 'Organized Crime', path: 'organized-crime' },
    { name: 'Parody', path: 'parody' },
    { name: 'Performing Arts', path: 'performing-arts' },
    { name: 'Pets', path: 'pets' },
    { name: 'Police', path: 'police' },
    { name: 'Psychological', path: 'psychological' },
    { name: 'Racing', path: 'racing' },
    { name: 'Reincarnation', path: 'reincarnation' },
    { name: 'Romance', path: 'romance' },
    { name: 'Romantic Subtext', path: 'romantic-subtext' },
    { name: 'Samurai', path: 'samurai' },
    { name: 'School', path: 'school' },
    { name: 'Sci-Fi', path: 'sci-fi' },
    { name: 'Seinen', path: 'seinen' },
    { name: 'Shoujo', path: 'shoujo' },
    { name: 'Shoujo Ai', path: 'shoujo-ai' },
    { name: 'Shounen', path: 'shounen' },
    { name: 'Showbiz', path: 'showbiz' },
    { name: 'Slice of Life', path: 'slice-of-life' },
    { name: 'Space', path: 'space' },
    { name: 'Sports', path: 'sports' },
    { name: 'Strategy Game', path: 'strategy-game' },
    { name: 'Strong Male Lead', path: 'strong-male-lead' },
    { name: 'Super Power', path: 'super-power' },
    { name: 'Supernatural', path: 'supernatural' },
    { name: 'Survival', path: 'survival' },
    { name: 'Suspense', path: 'suspense' },
    { name: 'System', path: 'system' },
    { name: 'Team Sports', path: 'team-sports' },
    { name: 'Thriller', path: 'thriller' },
    { name: 'Time Travel', path: 'time-travel' },
    { name: 'Vampire', path: 'vampire' },
    { name: 'Video Game', path: 'video-game' },
    { name: 'Villain', path: 'villain' },
    { name: 'Visual Arts', path: 'visual-arts' },
    { name: 'Work Life', path: 'work-life' },
    { name: 'Workplace', path: 'workplace' },
    { name: 'Yaoi', path: 'yaoi' },
    { name: 'Yuri', path: 'yuri' },
  ];
